window.I18N = {
  "zh-Hans": {
    ui: {
      appName: "Squirrel",
      common: {
        back: "返回",
      },
      nav: {
        home: "Home",
        dashboard: "Dashboard",
        settings: "Settings",
      },
      home: {
        heroPrefix: "随处抓取",
        heroEmphasis: "任何内容",
        heroSuffix: "。",
        subtitle: "粘贴链接，即刻开始高质量下载。",
        inputPlaceholder: "粘贴 YouTube、X 或 Bilibili 链接...",
        launchButton: "Launch",
        analyzing: "正在分析网络流...",
        compatiblePlatforms: "兼容平台",
        youtube: "YouTube",
        xcom: "X.com",
        bilibili: "Bilibili",
      },
      details: {
        breadcrumbSearch: "搜索",
        title: "视频详情",
        copyLink: "复制链接",
        tip: "Squirrel Engine: 选择最高质量快速下载，或显示全部流自行选择。",
        qualityProfile: "清晰度方案",
        maxQuality: "最高质量",
        allAvailable: "全部可选",
        outputFormat: "输出格式",
        videoAudio: "视频+音频",
        videoOnly: "仅视频",
        audioOnly: "仅音频",
        availableStreams: "可用流",
        ready: "就绪",
        totalSelected: "已选择",
        selectionSummary: "{count} Stream - {size}",
        downloadAll: "全部下载",
        freeSpaceHint: "剩余空间取决于磁盘。",
        diskSpace: "磁盘剩余：{free} / {total}",
        sourcePrefix: "来源：",
        uploadedPrefix: "上传",
      },
      dashboard: {
        title: "下载",
        activeCount: "{count} Active",
        pausedCount: "{count} Pause",
        totalSpeed: "Total Speed",
        filters: {
          downloading: "正在下载",
          completed: "已完成",
          history: "下载记录",
        },
        pauseAll: "Pause All",
        clearFinished: "Clear Finished",
        completedMeta: "大小 {size} · 完成 {time} · 来源 {source}",
        history: {
          searchPlaceholder: "搜索历史记录...",
          statusAll: "全部状态",
          statusCompleted: "已完成",
          statusFailed: "失败",
          statusCancelled: "已取消",
          platformAll: "全部平台",
          platformYouTube: "YouTube",
          platformX: "X.com",
          platformBilibili: "Bilibili",
          sortNewest: "最新优先",
          sortOldest: "最早优先",
          clear: "清空历史",
          empty: "暂无历史记录。",
          actionOpen: "显示在文件夹中",
          actionPlay: "播放",
          actionDelete: "删除记录",
          labelFinished: "完成时间",
          labelSize: "文件大小",
          labelAudio: "音频提取",
          audioYes: "是",
          audioNo: "否",
        },
      },
      settings: {
        title: "通用设置",
        subtitle: "管理下载偏好与应用行为。",
        downloadLocation: "下载位置",
        downloadLocationDesc: "设置下载文件保存目录。",
        defaultSavePath: "默认保存路径",
        change: "更改...",
        qualityPreferences: "清晰度偏好",
        qualityDesc: "设置默认下载分辨率。",
        defaultVideoQuality: "默认视频质量",
        preferredAudioFormat: "偏好音频格式",
        videoQualityOptions: {
          best: "最佳可用 (自动)",
          u2160: "4K UHD (2160p)",
          u1440: "2K QHD (1440p)",
          u1080: "全高清 (1080p)",
          u720: "高清 (720p)",
        },
        audioFormatOptions: {
          mp3: "高品质 (MP3 320kbps)",
          flac: "无损 (FLAC)",
          m4a: "标准 (M4A)",
        },
        language: "语言",
        languageDesc: "选择界面显示语言。",
        languageLabel: "界面语言",
        languageOptions: {
          zhHans: "简体中文",
          zhHant: "繁体中文",
          en: "English",
        },
        appBehavior: "应用行为",
        appBehaviorDesc: "设置应用与系统交互方式。",
        launchAtStartup: "开机启动",
        launchAtStartupDesc: "登录后自动启动 Squirrel。",
        desktopNotifications: "桌面通知",
        desktopNotificationsDesc: "下载完成时显示通知。",
        darkMode: "深色模式",
        darkModeDesc: "在浅色与深色主题间切换。",
        checkUpdates: "检查更新",
        statusUpToDate: "已是最新版本 (v{version})",
        aboutTitle: "Squirrel 桌面版",
        aboutVersion: "版本 {version}",
        privacy: "隐私政策",
        terms: "服务条款",
        help: "帮助中心",
        stableRelease: "稳定版",
      },
    },
    errors: {
      emptyUrl: "请输入有效链接。",
      ffmpegRequiredTitle: "需要 FFmpeg",
      ffmpegRequiredBody: "提取音频需要安装 ffmpeg。",
      ffmpegMissingTitle: "未安装 FFmpeg",
      ffmpegMissingBody: "合并音视频或提取音频需要 ffmpeg。",
      downloadFailed: "下载失败",
      openFailed: "打开失败",
      openFailedMissingPath: "缺少文件路径",
      openFailedGeneric: "无法打开",
    },
    info: {
      linkCopiedTitle: "已复制链接",
      linkCopiedBody: "复制完成",
      downloadStartedTitle: "开始下载",
      downloadCompletedTitle: "下载完成",
      openedFolderTitle: "已打开文件夹",
    },
    labels: {
      noStreams: "当前模式下没有可用流。",
      noTasks: "暂无任务。",
      statusDownloading: "下载中",
      statusPaused: "已暂停",
      statusCompleted: "已完成",
      statusFailed: "失败",
      statusCancelled: "已取消",
      statusPending: "等待中",
      stageDownloadingVideo: "下载视频",
      stageDownloadingAudio: "下载音频",
      stageDownloading: "下载中",
      stageMerging: "组装中",
      stageExtractingAudio: "提取音频",
      stageProcessing: "处理中",
      stagePaused: "已暂停",
      stageCompleted: "已完成",
      stageFailed: "失败",
      stageCancelled: "已取消",
      stagePending: "等待中",
    },
  },
  "zh-Hant": {
    ui: {
      appName: "Squirrel",
      common: {
        back: "返回",
      },
      nav: {
        home: "Home",
        dashboard: "Dashboard",
        settings: "Settings",
      },
      home: {
        heroPrefix: "隨處抓取",
        heroEmphasis: "任何內容",
        heroSuffix: "。",
        subtitle: "貼上連結，即刻開始高品質下載。",
        inputPlaceholder: "貼上 YouTube、X 或 Bilibili 連結...",
        launchButton: "Launch",
        analyzing: "正在分析網路串流...",
        compatiblePlatforms: "相容平台",
        youtube: "YouTube",
        xcom: "X.com",
        bilibili: "Bilibili",
      },
      details: {
        breadcrumbSearch: "搜尋",
        title: "影片詳情",
        copyLink: "複製連結",
        tip: "Squirrel Engine: 選擇最高品質快速下載，或顯示全部串流自行挑選。",
        qualityProfile: "畫質方案",
        maxQuality: "最高品質",
        allAvailable: "全部可選",
        outputFormat: "輸出格式",
        videoAudio: "影片+音訊",
        videoOnly: "僅影片",
        audioOnly: "僅音訊",
        availableStreams: "可用串流",
        ready: "就緒",
        totalSelected: "已選擇",
        selectionSummary: "{count} Stream - {size}",
        downloadAll: "全部下載",
        freeSpaceHint: "剩餘空間取決於磁碟。",
        diskSpace: "磁碟剩餘：{free} / {total}",
        sourcePrefix: "來源：",
        uploadedPrefix: "上傳",
      },
      dashboard: {
        title: "下載",
        activeCount: "{count} Active",
        pausedCount: "{count} Pause",
        totalSpeed: "Total Speed",
        filters: {
          downloading: "正在下載",
          completed: "已完成",
          history: "下載記錄",
        },
        pauseAll: "Pause All",
        clearFinished: "Clear Finished",
        completedMeta: "大小 {size} · 完成 {time} · 來源 {source}",
        history: {
          searchPlaceholder: "搜尋歷史記錄...",
          statusAll: "全部狀態",
          statusCompleted: "已完成",
          statusFailed: "失敗",
          statusCancelled: "已取消",
          platformAll: "全部平台",
          platformYouTube: "YouTube",
          platformX: "X.com",
          platformBilibili: "Bilibili",
          sortNewest: "最新優先",
          sortOldest: "最早優先",
          clear: "清空歷史",
          empty: "暫無歷史記錄。",
          actionOpen: "在資料夾顯示",
          actionPlay: "播放",
          actionDelete: "刪除記錄",
          labelFinished: "完成時間",
          labelSize: "檔案大小",
          labelAudio: "音訊擷取",
          audioYes: "是",
          audioNo: "否",
        },
      },
      settings: {
        title: "一般設定",
        subtitle: "管理下載偏好與應用行為。",
        downloadLocation: "下載位置",
        downloadLocationDesc: "設定下載檔案保存目錄。",
        defaultSavePath: "預設保存路徑",
        change: "變更...",
        qualityPreferences: "畫質偏好",
        qualityDesc: "設定預設下載解析度。",
        defaultVideoQuality: "預設影片品質",
        preferredAudioFormat: "偏好音訊格式",
        videoQualityOptions: {
          best: "最佳可用 (自動)",
          u2160: "4K UHD (2160p)",
          u1440: "2K QHD (1440p)",
          u1080: "Full HD (1080p)",
          u720: "HD (720p)",
        },
        audioFormatOptions: {
          mp3: "高品質 (MP3 320kbps)",
          flac: "無損 (FLAC)",
          m4a: "標準 (M4A)",
        },
        language: "語言",
        languageDesc: "選擇介面顯示語言。",
        languageLabel: "介面語言",
        languageOptions: {
          zhHans: "簡體中文",
          zhHant: "繁體中文",
          en: "English",
        },
        appBehavior: "應用行為",
        appBehaviorDesc: "設定應用與系統互動方式。",
        launchAtStartup: "開機啟動",
        launchAtStartupDesc: "登入後自動啟動 Squirrel。",
        desktopNotifications: "桌面通知",
        desktopNotificationsDesc: "下載完成時顯示通知。",
        darkMode: "深色模式",
        darkModeDesc: "在淺色與深色主題間切換。",
        checkUpdates: "檢查更新",
        statusUpToDate: "已是最新版本 (v{version})",
        aboutTitle: "Squirrel 桌面版",
        aboutVersion: "版本 {version}",
        privacy: "隱私政策",
        terms: "服務條款",
        help: "幫助中心",
        stableRelease: "穩定版",
      },
    },
    errors: {
      emptyUrl: "請輸入有效連結。",
      ffmpegRequiredTitle: "需要 FFmpeg",
      ffmpegRequiredBody: "擷取音訊需要安裝 ffmpeg。",
      ffmpegMissingTitle: "未安裝 FFmpeg",
      ffmpegMissingBody: "合併音視頻或擷取音訊需要 ffmpeg。",
      downloadFailed: "下載失敗",
      openFailed: "開啟失敗",
      openFailedMissingPath: "缺少檔案路徑",
      openFailedGeneric: "無法開啟",
    },
    info: {
      linkCopiedTitle: "已複製連結",
      linkCopiedBody: "複製完成",
      downloadStartedTitle: "開始下載",
      downloadCompletedTitle: "下載完成",
      openedFolderTitle: "已開啟資料夾",
    },
    labels: {
      noStreams: "目前模式下沒有可用串流。",
      noTasks: "沒有任務。",
      statusDownloading: "下載中",
      statusPaused: "已暫停",
      statusCompleted: "已完成",
      statusFailed: "失敗",
      statusCancelled: "已取消",
      statusPending: "等待中",
      stageDownloadingVideo: "下載影片",
      stageDownloadingAudio: "下載音訊",
      stageDownloading: "下載中",
      stageMerging: "組裝中",
      stageExtractingAudio: "擷取音訊",
      stageProcessing: "處理中",
      stagePaused: "已暫停",
      stageCompleted: "已完成",
      stageFailed: "失敗",
      stageCancelled: "已取消",
      stagePending: "等待中",
    },
  },
  en: {
    ui: {
      appName: "Squirrel",
      common: {
        back: "Back",
      },
      nav: {
        home: "Home",
        dashboard: "Dashboard",
        settings: "Settings",
      },
      home: {
        heroPrefix: "Grab anything from",
        heroEmphasis: "anywhere",
        heroSuffix: ".",
        subtitle: "Paste a URL to start your high-quality download.",
        inputPlaceholder: "Paste YouTube, X, or Bilibili link here...",
        launchButton: "Launch",
        analyzing: "Analyzing network stream...",
        compatiblePlatforms: "Compatible Platforms",
        youtube: "YouTube",
        xcom: "X.com",
        bilibili: "Bilibili",
      },
      details: {
        breadcrumbSearch: "Search",
        title: "Video Details",
        copyLink: "Copy Link",
        tip: "Squirrel Engine: choose Max Quality for a quick best pick, or show all streams to decide manually.",
        qualityProfile: "Quality Profile",
        maxQuality: "Max Quality",
        allAvailable: "All Available",
        outputFormat: "Output Format",
        videoAudio: "Video+Audio",
        videoOnly: "Video Only",
        audioOnly: "Audio",
        availableStreams: "Available Streams",
        ready: "Ready",
        totalSelected: "Total Selected",
        selectionSummary: "{count} Stream - {size}",
        downloadAll: "Download All",
        freeSpaceHint: "Free space depends on your disk.",
        diskSpace: "Disk Free: {free} / {total}",
        sourcePrefix: "Source:",
        uploadedPrefix: "Uploaded",
      },
      dashboard: {
        title: "Downloads",
        activeCount: "{count} Active",
        pausedCount: "{count} Pause",
        totalSpeed: "Total Speed",
        filters: {
          downloading: "Downloading",
          completed: "Completed",
          history: "History",
        },
        pauseAll: "Pause All",
        clearFinished: "Clear Finished",
        completedMeta: "Size {size} · Finished {time} · Source {source}",
        history: {
          searchPlaceholder: "Search history...",
          statusAll: "All Status",
          statusCompleted: "Completed",
          statusFailed: "Failed",
          statusCancelled: "Cancelled",
          platformAll: "All Platforms",
          platformYouTube: "YouTube",
          platformX: "X.com",
          platformBilibili: "Bilibili",
          sortNewest: "Newest",
          sortOldest: "Oldest",
          clear: "Clear History",
          empty: "No history records.",
          actionOpen: "Show in folder",
          actionPlay: "Play",
          actionDelete: "Delete record",
          labelFinished: "Finished",
          labelSize: "Size",
          labelAudio: "Audio extracted",
          audioYes: "Yes",
          audioNo: "No",
        },
      },
      settings: {
        title: "General",
        subtitle: "Manage your download preferences and application behavior.",
        downloadLocation: "Download Location",
        downloadLocationDesc: "Choose where your downloaded files will be stored.",
        defaultSavePath: "Default save path",
        change: "Change...",
        qualityPreferences: "Quality Preferences",
        qualityDesc: "Set the default resolution for new downloads.",
        defaultVideoQuality: "Default Video Quality",
        preferredAudioFormat: "Preferred Audio Format",
        videoQualityOptions: {
          best: "Best Available (Auto)",
          u2160: "4K UHD (2160p)",
          u1440: "2K QHD (1440p)",
          u1080: "Full HD (1080p)",
          u720: "HD (720p)",
        },
        audioFormatOptions: {
          mp3: "High Quality (MP3 320kbps)",
          flac: "Lossless (FLAC)",
          m4a: "Standard (M4A)",
        },
        language: "Language",
        languageDesc: "Select your interface language.",
        languageLabel: "App Language",
        languageOptions: {
          zhHans: "Simplified Chinese",
          zhHant: "Traditional Chinese",
          en: "English",
        },
        appBehavior: "App Behavior",
        appBehaviorDesc: "Control how the application interacts with your system.",
        launchAtStartup: "Launch at Startup",
        launchAtStartupDesc: "Automatically start Squirrel when you log in.",
        desktopNotifications: "Desktop Notifications",
        desktopNotificationsDesc: "Show a notification when a download is finished.",
        darkMode: "Dark Mode",
        darkModeDesc: "Switch between light and dark visual styles.",
        checkUpdates: "Check for Updates",
        statusUpToDate: "Up to date (v{version})",
        aboutTitle: "Squirrel for Desktop",
        aboutVersion: "Version {version}",
        privacy: "Privacy Policy",
        terms: "Terms of Service",
        help: "Help Center",
        stableRelease: "Stable Release",
      },
    },
    errors: {
      emptyUrl: "Please enter a URL.",
      ffmpegRequiredTitle: "FFmpeg required",
      ffmpegRequiredBody: "Audio extraction needs ffmpeg. Install it to continue.",
      ffmpegMissingTitle: "FFmpeg missing",
      ffmpegMissingBody: "Install ffmpeg to merge audio/video or extract audio.",
      downloadFailed: "Download failed",
      openFailed: "Open failed",
      openFailedMissingPath: "File path missing",
      openFailedGeneric: "Unable to open",
    },
    info: {
      linkCopiedTitle: "Link copied",
      linkCopiedBody: "Copy completed",
      downloadStartedTitle: "Download started",
      downloadCompletedTitle: "Download completed",
      openedFolderTitle: "Opened folder",
    },
    labels: {
      noStreams: "No streams available for this mode.",
      noTasks: "No tasks available.",
      statusDownloading: "Downloading",
      statusPaused: "Paused",
      statusCompleted: "Completed",
      statusFailed: "Failed",
      statusCancelled: "Cancelled",
      statusPending: "Pending",
      stageDownloadingVideo: "Downloading video",
      stageDownloadingAudio: "Downloading audio",
      stageDownloading: "Downloading",
      stageMerging: "Assembling",
      stageExtractingAudio: "Extracting audio",
      stageProcessing: "Processing",
      stagePaused: "Paused",
      stageCompleted: "Completed",
      stageFailed: "Failed",
      stageCancelled: "Cancelled",
      stagePending: "Pending",
    },
  },
};

window.STRINGS = window.I18N["zh-Hans"];
